### ISSUE TITLE
0 backups but Account has run out of space

### ISSUE THREAD

**Issue by tukoz** [conformal/cyphertite#112]
Hi,
After I deleted all of my Cyphertite's backups, they're still counted present by cyphertite, which prevents me to do any new backup :/
Before deletion:

```
Used Space:    61.12%    4.89 GB of 8 GB 

$ cyphertite -me <md_filename>
$ ctctl cull [x2]
$ cyphertite -mt
867 Nov 10 18:49    crypto.secret
```

But
1. My Account still shows
   
   ```
   Used Space:    61.12%    4.89 GB of 8 GB 
   ```
2. The 1 MB backup I'm trying to run always ends up with:
   
   ```
   $ ct -E <EXCLUDE> -cHf <md_backup> /path_to_the_1MB_folder_to_backup/
   chunk write failed: Account has run out of space - Please log in to your cyphertite.com account or contact support@cyphertite.com
   ```

Please what am I doing wrong?
Why are the deleted files still (counted) on your servers? And how the ~1 MB backup results in the above message?
I've read issues #50 and #90 to #93 which are slightly different (`ct -mt` listed these clients' backups)

cyphertite.conf:

```
ctfile_mode       = remote
ctfile_remote_auto_incremental  = 1
ctfile_max_incrementals = 7
ctfile_cull_keep_days = 30
ctfile_differential_allfiles    = 0
```

**Comment by SirHumphreyAppleby** [comment]
I can confirm I also had this issue with the free account. I assumed it was due to my account initially being cancelled and then reactivated. I had hoped to use that account name for my subscription, but due to that problem I used another one I had created while I waited for the reactivation.

Data is not deleted immediately. If you delete a backup and recreate it, deduplication will still happen. What triggers the server-side deletion I don't know, but I don't think anything 'deleted' should be counted against your quota, and even if retained for a period, should be silently deleted without any interaction from the client. Hopefully one of the developers will give us a bit more insight in to how this works (or is meant to work).

**Comment by tukoz** [comment]
Thank you SirHumphrey for confirming a rather strange issue, and nicely describing what a user expects.

ps I'm still testing cyphertite before going _pro_ with it eventualy.

**Comment by marcopeereboom** [comment]
We will have a look at this.  Thank you for reporting.

**Comment by tukoz** [comment]
Hi, situation's stalled ie no possible backup. Any news welcome :+1:

**Comment by tukoz** [comment]
Back to work since yesterday, thanks you.
