### ISSUE TITLE
ctfb bug when / itself is explicitly backed up

### ISSUE THREAD

**Issue by csmiken** [conformal/cyphertite#41]
Unable to browse into an archive using ctfb when / itself is explicitly backed up.

**Comment by owainga** [comment]
The issue here is rather silly, sadly. The chdir code in ctfb assumes that we never have an entry named after the directory separator. This is 100% true unless / itself is backed up when we store a directory entry for the root directory explicitly.

I am working out how to fix this. Hopefully a fix soon.
