### ISSUE TITLE
What's the recommended way to do incremental backups to cyphertite servers?

### ISSUE THREAD

**Issue by gabeguz** [conformal/cyphertite#50]
I'm trying this at the moment: 

Initial backup:
cyphertite -cf desktop.home.gabe.ct /home/gabe

Incremental: 
cyphertite -B desktop.home.gabe.ct -cf desktop.home.gabe.ct /home/gabe

That returns this: 
incremental basis in remote mode

And then exits.

I can redo the same initial command:  
cyphertite -cf desktop.home.gabe.ct /home/gabe

And I'll then see 2 backups in the remote: 

gabe@desktop:~$ cyphertite -mt
29256720 Jul 25 02:09   20130723-010425-desktop.home.gabe.ct
23404440 Oct 10 14:06   20131010-020523-desktop.home.gabe.ct

But they both seem to be _full_ backups. 

Is incremental limited to local ct files only? 

I currently have: 
ctfile_mode                             = remote
ctfile_remote_auto_incremental          = 1

in my cyphertite.conf file. 

Don't want to waste space on your servers for no reason, if there is a better way.

Thanks,
gabe.

**Comment by csmiken** [comment]
Good question. I want to point out that it appears that your setup is correct for your ask. "-B" is not necessary when you are using "ctfile_remote_auto_incremental = 1" and remote mode. In fact, I want to point out that we are in the process of removing "ctfile_mode = local" and "-B" as they are no longer a good idea for reasons...

If you name the backup (ctfile) the same as a previous one, then it will be created as an incremental. You should notice that the backup completes much faster and the size of that ctfile will be much smaller depending on the amount of data that changed. I suggest you set: "ctfile_max_incrementals" to how many you want before Cyphertite automatically does another full backup and starts building incrementals again. This way you can use the same Cyphertite command each time you make a backup and the behavior you want will happen automatically.

Something else to point out is: Because of deduplication, Cyphertite will be sending a minimum of chunks to our servers in either backup case, full or incremental. The above discussion will only affect the size of your ctfiles.

Is there anything else that needs more explanation here?

**Comment by gabeguz** [comment]
Ok, great... so I'm doing everything correctly, just wanted to confirm.  
Nothing else needs explanation, thanks for your response.
