### ISSUE TITLE
[solved] Max differentials backup option?

### ISSUE THREAD

**Issue by tukoz** [conformal/cyphertite#93]
Hi, 
Please how to configure cyphertite so that we'll do a daily incremental backup over a limited period of time?
i.e. as in this [example by calyptix](http://blog.calyptix.com/2012/04/getting-started-with-cyphertite-remote.html), which use defunct ~~ctfile_max_differentials~~ option?
/me have trouble figuring out how to do that using cyphertite man page and the  configuration doc :sweat_drops:

**Comment by csmiken** [comment]
What do you mean by "over a limited period of time"?

**Comment by tukoz** [comment]
Hi csmiken

Here is an example scenario with "over a limited period of time" = a month:

> ct -cvRf BACKUP_1.ct /<DIR>
> ctfile_max_differentials = 29 
> ctfile_cull_keep_days = 30 

i.e. run 29 incremental backups, then force a level 0, then run 29 more incremental backups, etc. Assuming a daily job, it will run a full backup once a month, and incrementals in between. The second line will auto-delete old ctfiles for you after the specified time period, as well as their associated data (if unreferenced by other ctfiles). So in this example we tell cyphertite to keep only 30 days worth of ctfiles and data.

Hope it makes more sense.

**Comment by csmiken** [comment]
Your example is correct. One thing to keep in mind is that every backup will create a ctfile. When you do run cull, Cyphertite will not remove any ctfiles when another depends on it.

Cyphertite does use a good deduplication method. This means that each backup will only send data to our servers if it is new or altered since the last backup. Because of this, running incrementals will save less space then a non-deduplicated backup solution. I recommend setting max incrementals to 7, and keep days to 30.

**Comment by tukoz** [comment]
Thank you csmiken.
In order to achieve the scenario above I replaced '_ctfile_max_differentials_' with '_ctfile_max_incrementals_' in cyphertite's conf.

**Comment by tharrisone** [comment]
By default, if I cyphertite -E /home/meh/exclude.txt -cRv -f homedir.ct /home/meh is every backup a full backup? Is there a compete tutorial around, as the wiki only has a few tips. I'm getting my feet wet.
